# Generated by Django 3.2 on 2021-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210528_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail1',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail3',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
